### ISSUE TITLE
Can this be used to import old d3d files into Blender?

### ISSUE THREAD

**Issue by torrinworx** [massivecatapult/gamemaker-3d-io#1]
I'm taking a look at an old game that was made with Gamemaker and has a lot of d3d files, was wondering if this is supported?

**Comment by massivecatapult** [comment]
Hi @torrinworx - this project currently only takes Blender models and converts them to vertex buffers (or GML). It probably wouldn't be too hard to write a script in Python (or even GameMaker, assuming that's the source of your D3D files) that would convert them though.
